#!/usr/bin/env php
<?php
// From: http://collectiveidea.com/blog/archives/2010/08/03/happy-git-commits/
$dir = __DIR__;
if (!file_exists("$dir/success.mp3")) {
    `ln -s $dir/happykids.wav $dir/success.mp3`;
}
if (`uname` === 'Darwin') {
    $command = "afplay $dir/success.mp3 > /dev/null 2>&1 &";
} else {
    $command = "play $dir/success.mp3 > /dev/null 2>&1 &";
}
exec($command);
exit(0);
